################################
# MCP Docker Developer Server
# Supported GPUS: AMD and NVIDIA GPU supported, Intel Not supported.
# This services creates the server
# NOTE: PLEASE CHECK FOR FEATURES YOU WANT
#.                              #
# Learn more in Documentation   #
#                               #
#                               #
#################################

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    ports:
      - 8888:8080
    networks:
      - mcp-network
    volumes:
      - ./config:/etc/searxng/
      - ./data:/var/cache/searxng/
      - ./static_assets/settings.yml:/usr/local/searxng/searx/settings.yml # enable API features by replacing internal settings.yml with a modified version
    restart: always
  devdocs:
    image: ghcr.io/freecodecamp/devdocs:latest-alpine
    container_name: devdocs
    ports:
      - 9292:9292
    networks:
      - mcp-network
    volumes:
      - devdocs-data:/app/.devdocs
    restart: always
  auto-sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    container_name: devdocs-sync
    volumes:
      - devdocs-data:/app/.devdocs
    networks:
      - mcp-network
    restart: always
  mcp-server:
    build:
      context: .
    privileged: true
    restart: always
    ports:
      - 8000:8000
    user: "0:0" # Run as root to access Docker socket
    # --- GPU support [NVIDIA] Uncomment this section out if you want these features ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all # (change this to the amount you want.)
    #           capabilities: [gpu]
    # --- GPU support [AMD] ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: rocm
    #           count: all # or a seperate amount
    #           capabilities: [gpu]

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # giving access to Docker Socket
    networks:
      - mcp-network
    depends_on:
      - devdocs
      - searxng
    environment:
      - DEVDOCS_URL=http://devdocs:9292
      - SEARXNG_URL=http://searxng:8080
      - REDIS_URL=http://redis:6397
      # --- Firecrawl [Local] ---
      # - FIRECRAWL_URL=http://firecrawl:3002
      # - ENABLE_FIRECRAWL=true
      # --- Firecrawl [API] ---
      # - ENABLE_FIRECRAWL=true
      # - FIRECRAWL_API_KEY=<API_KEY_HERE>
      # Comment ENABLE_FIRECRAWL=false out if you are using the top two Firecrawl subfeatures
      - ENABLE_FIRECRAWL=false
      - ENABLE_MCP_OAUTH=true # OAuth 2.1 authentication enabled
      - MCP_OAUTH_AUTHORIZATION_SERVER=http://mcp-server:8000 # Self-hosted auth server
      - MCP_OAUTH_ISSUER=http://mcp-server:8000
      - MCP_OAUTH_RESOURCE_URI=http://mcp-server:8000
      - MCP_OAUTH_CLIENT_ID=mcp-docker-server-default
      - MCP_OAUTH_CLIENT_SECRET=mcp_secret_key_change_in_production_2024
      - MCP_OAUTH_CLIENT_NAME="MCP Docker Dev Server"
      - MCP_OAUTH_TOKEN_EXPIRY=3600
      - MCP_OAUTH_SCOPE=mcp:read mcp:write mcp:admin
      - MCP_OAUTH_REQUIRE_HTTPS=false # Set to true in production with HTTPS
      - MCP_OAUTH_DYNAMIC_REGISTRATION=true
      - MCP_OAUTH_ENABLE_PKCE=true
      - MCP_OAUTH_REQUIRE_AUTH=true # Require authentication for protected resources
  redis:
    image: redis:alpine
    ports:
      - 6397:6379
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - mcp-network
volumes:
  devdocs-data:

  redis-data:

networks:
  mcp-network:
    driver: bridge
