services:
  mcp-server:
    build:
      context: .
    privileged: true
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mcp-network
    depends_on:
      - devdocs
    environment:
      - DEVDOCS_URL=http://devdocs:9292

  devdocs:
    image: ghcr.io/freecodecamp/devdocs:latest-alpine
    container_name: devdocs
    ports:
      - "9292:9292"
    networks:
      - mcp-network
    volumes:
      - devdocs-data:/app/.devdocs

  auto-sync:
    build:
      context: .
      dockerfile: Dockerfile.sync
    container_name: devdocs-sync
    volumes:
      - devdocs-data:/app/.devdocs
    networks:
      - mcp-network

volumes:
  devdocs-data:

networks:
  mcp-network:
    driver: bridge
